#!/usr/bin/env sh
# Create disk image for melonDS.
# Run from repo root.

# create and format
i=test/en.img
dd if=/dev/zero of=$i bs=1M count=4
mformat -i $i

# populate
mmd -i $i book
mcopy -i $i test/en/*.epub ::book
mmd -i $i font
mcopy -i $i test/en/*.ttf ::font

# verify
mdir -i $i
mdir -i $i book
mdir -i $i font
