#!/usr/bin/env sh

if [ $(uname) == 'Linux' && -f /etc/debian_version ]
then
	sudo apt install wget gdebi-core -y
	
	wget https://github.com/devkitPro/pacman/releases/download/v1.0.2/devkitpro-pacman.amd64.deb
	sudo gdebi devkitpro-pacman.amd64.deb
fi

sudo dkp-pacman -S default-arm7 devkitARM devkitarm-crtls devkitarm-rules devkitpro-keyring dstools grit libfat-nds libnds nds-bzip2 nds-freetype nds-libexpat nds-libpng nds-pkg-config nds-zlib ndstool 

