# Compact flash image file for emulation.
CFLASH_IMAGE		:=	cflash.img
# Path to media card.
MEDIA_MOUNTPOINT	:= /media/CYCLODS

EMULATOR := desmume-cli

.PHONY: image

# Create a cflash test image for use with emulator.
$(CFLASH_IMAGE):
	dd if=/dev/zero of=$(CFLASH_IMAGE) bs=1048576 count=8
	/sbin/mkfs.vfat $(CFLASH_IMAGE)
	mkdir /tmp/cflash
	mount $(CFLASH_IMAGE) /tmp/cflash
	cp cflash/* /tmp/cflash
	sync
	umount /tmp/cflash
	rmdir /tmp/cflash

image: $(CFLASH_IMAGE)
