#!/usr/bin/env sh
#
# Run this from within the cairo source dir:
#   cd cairo-1.6.0
#   ../congfigure-cairo

./configure --prefix=$(realpath ..) --host=arm-none-eabi \
--enable-xlib=no \
--enable-xlib-xrender=no \
--enable-xcb=no \
--enable-xlib-xcb=no \
--enable-xcb-shm=no \
--enable-glx=no \
--enable-pdf=no \
--enable-png=yes \
--enable-ps=yes \
--enable-ft=yes \
--enable-fc=no \
--enable-pthread=no \
--enable-gobject=no \
CPPFLAGS="-I$(realpath ../include) -DCAIRO_NO_MUTEX=1" \
LDFLAGS="-L$(realpath ../lib)" \
PKG_CONFIG_PATH=../lib/pkgconfig 

