#!/usr/bin/env sh

PATH=$DEVKITARM/bin:$PATH
prefix=$(cd .. && pwd)
portlibs=$DEVKITPRO/portlibs/nds

./configure --prefix=$prefix --host=arm-none-eabi \
CPPFLAGS="-I$portlibs/include" LDFLAGS="-L$portlibs/lib"
