#ifndef _NDSX_BRIGHTNESS_
#define _NDSX_BRIGHTNESS_
#include <nds.h>

#define BACKLIGHT_FIFO FIFO_USER_08
#define PM_DSLITE_REG   (4)
#define PM_IS_LITE      BIT(6)
#define PM_BACKLIGHTS   (PM_BACKLIGHT_BOTTOM | PM_BACKLIGHT_TOP)


#endif // _NDSX_BRIGHTNESS_

